export type JarCard = { kind: 'Challenge' | 'Create' | 'Kindness' | 'Silly' | 'Calm' | 'Think'; text: string };

// The boredom jar: quick things to do instead of scrolling.
export const JAR: JarCard[] = [
  { kind: 'Challenge', text: 'Plank for 30 seconds. Then try 45.' },
  { kind: 'Challenge', text: 'Name 10 fruits in 30 seconds, out loud.' },
  { kind: 'Challenge', text: 'Find 5 things in your room that are green.' },
  { kind: 'Challenge', text: 'Memorise one short ayah before your next prayer.' },
  { kind: 'Challenge', text: 'Tidy one drawer. Only one. Set a 7-minute timer.' },
  { kind: 'Challenge', text: 'Write your name in Arabic with your other hand.' },
  { kind: 'Create', text: 'Draw your dream room upstairs, with every detail.' },
  { kind: 'Create', text: 'Make a playlist of nasheeds or sounds that calm you.' },
  { kind: 'Create', text: 'Take one beautiful photo of something boring.' },
  { kind: 'Create', text: 'Invent a new chai recipe and give it a name.' },
  { kind: 'Create', text: 'Write a six-word story about your day.' },
  { kind: 'Create', text: 'Design a logo idea for Lotus on a scrap of paper.' },
  { kind: 'Kindness', text: 'Send Ammi a voice note saying one thing you love about her.' },
  { kind: 'Kindness', text: 'Make chai for whoever is awake.' },
  { kind: 'Kindness', text: 'Leave a sweet note on a sister’s pillow.' },
  { kind: 'Kindness', text: 'Make dua for three people by name, right now.' },
  { kind: 'Kindness', text: 'Ask Abbu about his childhood. Listen to the whole story.' },
  { kind: 'Kindness', text: 'Compliment your best friend on something specific.' },
  { kind: 'Silly', text: 'Talk in a different accent for the next 10 minutes.' },
  { kind: 'Silly', text: 'Teach someone at home a handshake you just invented.' },
  { kind: 'Silly', text: 'Rate every snack in the kitchen out of 10.' },
  { kind: 'Silly', text: 'Do your best impression of a family member (kindly).' },
  { kind: 'Silly', text: 'Dance badly to one song with the door closed.' },
  { kind: 'Calm', text: 'Lie on the floor for 3 minutes and just breathe.' },
  { kind: 'Calm', text: 'Go to the roof and watch the sky until something changes.' },
  { kind: 'Calm', text: 'Do 33 SubhanAllah, 33 Alhamdulillah, 34 Allahu Akbar slowly.' },
  { kind: 'Calm', text: 'Wash your face with cold water and put on something comfy.' },
  { kind: 'Calm', text: 'Listen to your favourite qari for one surah.' },
  { kind: 'Think', text: 'If you could learn any skill instantly, what would it be? Why?' },
  { kind: 'Think', text: 'What would you, ten years from now, thank you for doing this year?' },
  { kind: 'Think', text: 'Plan your perfect Saturday, hour by hour.' },
  { kind: 'Think', text: 'Which prophet’s story do you know least? Look it up.' },
  { kind: 'Think', text: 'List 5 foods you’ve never tried and want to.' },
  { kind: 'Think', text: 'What’s one small thing that would make your room feel like yours?' },
];

export type Question = { q: string; options: string[]; answer: number; note?: string };

export const QUIZ: Question[] = [
  { q: 'How many surahs are in the Quran?', options: ['99', '114', '120', '110'], answer: 1 },
  { q: 'Which is the longest surah?', options: ['Al-Imran', 'An-Nisa', 'Al-Baqarah', 'Yasin'], answer: 2 },
  { q: 'Which surah does not begin with Bismillah?', options: ['At-Tawbah', 'Al-Fatiha', 'Al-Kahf', 'Al-Mulk'], answer: 0 },
  { q: 'What was the first word revealed to the Prophet ﷺ?', options: ['Qul', 'Iqra', 'Alhamdulillah', 'Ya ayyuha'], answer: 1, note: 'Surah Al-ʿAlaq 96:1' },
  { q: 'Which surah is equal to a third of the Quran?', options: ['Al-Falaq', 'Al-Kawthar', 'Al-Ikhlas', 'An-Nas'], answer: 2, note: 'Sahih al-Bukhari 5013' },
  { q: 'What is the shortest surah?', options: ['Al-Asr', 'Al-Kawthar', 'An-Nasr', 'Al-Ikhlas'], answer: 1 },
  { q: 'Which woman is mentioned by name in the Quran?', options: ['Khadijah', 'Hawwa', 'Maryam', 'Asiya'], answer: 2 },
  { q: 'Which prophet was swallowed by a whale?', options: ['Musa', 'Yunus', 'Nuh', 'Ayyub'], answer: 1 },
  { q: 'Who built the Kaaba with his son?', options: ['Adam', 'Ibrahim', 'Sulayman', 'Dawud'], answer: 1, note: 'With Ismail, Al-Baqarah 2:127' },
  { q: 'What was the name of the Prophet’s ﷺ mother?', options: ['Aminah', 'Halimah', 'Fatimah', 'Khadijah'], answer: 0 },
  { q: 'Which angel brought the revelation?', options: ['Mikail', 'Israfil', 'Jibril', 'Malik'], answer: 2 },
  { q: 'Which city did the Prophet ﷺ migrate to?', options: ['Taif', 'Makkah', 'Madinah', 'Jerusalem'], answer: 2 },
  { q: 'How many juz are in the Quran?', options: ['20', '30', '40', '60'], answer: 1 },
  { q: 'How many fard rakat are in Maghrib?', options: ['2', '3', '4', '5'], answer: 1 },
  { q: 'The night better than a thousand months is…', options: ['Laylat al-Qadr', 'Night of Isra', 'Night of Eid', 'Shab-e-Barat'], answer: 0, note: 'Surah Al-Qadr 97:3' },
  { q: 'What was the first major battle in Islam?', options: ['Uhud', 'Khandaq', 'Badr', 'Hunayn'], answer: 2 },
  { q: 'Who was the first wife of the Prophet ﷺ?', options: ['Aisha', 'Khadijah', 'Sawdah', 'Hafsa'], answer: 1 },
  { q: 'Which prophet could understand the speech of ants?', options: ['Sulayman', 'Yusuf', 'Isa', 'Hud'], answer: 0, note: 'An-Naml 27:18–19' },
  { q: 'Which surah is named after a spider?', options: ['An-Naml', 'Al-Ankabut', 'An-Nahl', 'Al-Fil'], answer: 1 },
  { q: 'Which surah tells the story of the People of the Cave?', options: ['Maryam', 'Al-Kahf', 'Yusuf', 'Taha'], answer: 1 },
  { q: 'What is the capital of Turkey?', options: ['Istanbul', 'Ankara', 'Izmir', 'Bursa'], answer: 1 },
  { q: 'How many bones does an adult human have?', options: ['186', '206', '226', '256'], answer: 1 },
  { q: 'Which planet has the most known moons (2026)?', options: ['Jupiter', 'Saturn', 'Uranus', 'Mars'], answer: 1 },
  { q: 'Which is Pakistan’s highest mountain?', options: ['Nanga Parbat', 'K2', 'Broad Peak', 'Rakaposhi'], answer: 1 },
  { q: 'Honey never spoils. True?', options: ['True', 'False'], answer: 0, note: 'Sealed honey lasts for thousands of years.' },
  { q: 'Which bee is mentioned in a surah’s name?', options: ['An-Nahl means “the bee”', 'There is none'], answer: 0, note: 'Surah 16' },
];

export const MATCH_SYMBOLS = ['☾', '✦', '❀', '♡', '☀', '✿', '❋', '◈'];
